# add a docker compose file to run the database in a container of postgres db not on default port 5432

services:
  db:
    image: postgres:latest
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chaicodereviewer
  